"use client";

import {useState} from "react";
import AssistantChat from "../../../components/assistant-chat";
import {useAssistant} from "../../../components/assistant-context";
import CategorizationReview from "../../../components/categorization-review";
import {Panel,Pill} from "../../../components/ui";

export default function AssistantPage(){const assistant=useAssistant(),[view,setView]=useState<"chat"|"categorize">("chat");return <div><nav className="ledger-tabs" aria-label="Assistant workspace"><button className={view==="chat"?"active":""} onClick={()=>setView("chat")}>Ask Tallystead</button><button className={view==="categorize"?"active":""} onClick={()=>setView("categorize")}>Categorization review</button></nav>{view==="categorize"?<CategorizationReview/>:<div className="assistant-workspace"><Panel className="assistant-history"><div className="assistant-history-head"><span><p className="eyebrow">Stored locally</p><h2>Conversations</h2></span><button className="button compact primary" onClick={()=>void assistant.newConversation()}>New</button></div><div className="assistant-history-list">{assistant.conversations.map(item=><div className={assistant.conversationId===item.conversation_id?"active":""} key={item.conversation_id}><button onClick={()=>void assistant.selectConversation(item.conversation_id)}><b>{item.title}</b><small>{item.currency_code} · {item.ownership_scope}</small></button><button className="history-delete" aria-label={`Delete ${item.title}`} onClick={()=>void assistant.deleteConversation(item.conversation_id)}>×</button></div>)}</div><div className="assistant-boundary"><Pill tone="blue">Read-only</Pill><p>The assistant can read authorized reports and cite records. It has no financial write tools.</p></div></Panel><Panel className="assistant-main"><div className="assistant-main-head"><span><p className="eyebrow">Household-local AI</p><h2>{assistant.conversationId?"Conversation":"New conversation"}</h2></span><button className="button compact" disabled={!assistant.messages.length||assistant.status!=="ready"} onClick={()=>void assistant.regenerate()}>Regenerate</button></div><AssistantChat/></Panel></div>}</div>}
