"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAppSession } from "../../../../components/app-shell";
import { Notice, Panel, Pill } from "../../../../components/ui";
import { apiRequest, clearSession } from "../../../../lib/client";

type Member = { user_id: string; membership_id: string; email: string; display_name: string; role: string; is_active: boolean };
type Device = { session_id: string; user_id: string; device_name: string | null; created_at: string; expires_at: string; is_current: boolean };

export default function AccessPage() {
  const router = useRouter();
  const { serverUrl, session, me } = useAppSession();
  const [members, setMembers] = useState<Member[]>([]); const [devices, setDevices] = useState<Device[]>([]); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => {
    const [memberList, deviceList] = await Promise.all([
      apiRequest<Member[]>(serverUrl, "/v1/household/members", {}, session.access_token),
      apiRequest<Device[]>(serverUrl, "/v1/household/sessions", {}, session.access_token),
    ]);
    setMembers(memberList);
    setDevices(deviceList);
  }, [serverUrl, session.access_token]);
  useEffect(() => { void load(); }, [load]);
  async function role(member: Member, value: string) { setBusy(true); try { await apiRequest(serverUrl, `/v1/household/members/${member.membership_id}`, { method: "PATCH", body: JSON.stringify({ role: value }) }, session.access_token); await load(); setNotice(`${member.display_name}'s role was updated.`); } catch (e) { setNotice(e instanceof Error ? e.message : "Role update failed."); } finally { setBusy(false); } }
  async function toggle(member: Member) { setBusy(true); try { await apiRequest(serverUrl, `/v1/household/members/${member.membership_id}/status`, { method: "PATCH", body: JSON.stringify({ is_active: !member.is_active }) }, session.access_token); await load(); setNotice(`${member.display_name}'s account was ${member.is_active ? "disabled" : "enabled"}.`); } catch (e) { setNotice(e instanceof Error ? e.message : "Account update failed."); } finally { setBusy(false); } }
  async function reset(member: Member) { const password = window.prompt(`Set a temporary password for ${member.display_name} (12+ characters).`); if (!password) return; setBusy(true); try { await apiRequest(serverUrl, `/v1/household/members/${member.membership_id}/reset-password`, { method: "POST", body: JSON.stringify({ password }) }, session.access_token); setNotice("Password reset; existing sessions were revoked."); } catch (e) { setNotice(e instanceof Error ? e.message : "Reset failed."); } finally { setBusy(false); } }
  async function add(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const formElement = event.currentTarget; const form = new FormData(formElement); try { await apiRequest(serverUrl, "/v1/household/members", { method: "POST", body: JSON.stringify({ display_name: form.get("name"), email: form.get("email"), password: form.get("password"), role: form.get("role") }) }, session.access_token); formElement.reset(); await load(); setNotice("Household member added."); } catch (e) { setNotice(e instanceof Error ? e.message : "Member could not be added."); } finally { setBusy(false); } }
  async function revoke(device: Device) { setBusy(true); try { await apiRequest(serverUrl, `/v1/household/sessions/${device.session_id}`, { method: "DELETE" }, session.access_token); if (device.is_current) { clearSession(); router.replace("/"); return; } await load(); setNotice("Household device session revoked."); } catch (e) { setNotice(e instanceof Error ? e.message : "Session could not be revoked."); } finally { setBusy(false); } }
  function memberName(userId: string) { return members.find((member) => member.user_id === userId)?.display_name ?? "Household member"; }
  return <div className="grid"><Panel span={8}><p className="eyebrow">Role-based access</p><h2>Household members</h2><p className="muted">Permissions are enforced by the server for every protected operation.</p>{notice && <Notice title="Access update">{notice}</Notice>}<div>{members.map((member) => <div className="row member-row" key={member.membership_id}><div><b>{member.display_name}</b><small>{member.email}</small></div><div className="row-actions"><Pill tone={member.is_active ? "green" : "red"}>{member.is_active ? "Active" : "Disabled"}</Pill><select aria-label={`Role for ${member.display_name}`} value={member.role} disabled={busy || !member.is_active} onChange={(event) => role(member, event.target.value)}><option value="owner">Owner</option><option value="manager">Manager</option><option value="contributor">Contributor</option><option value="viewer">Viewer</option></select><button className="button compact" disabled={busy} onClick={() => reset(member)}>Reset password</button><button className="button compact" disabled={busy || member.user_id === me.user_id} onClick={() => toggle(member)}>{member.is_active ? "Disable" : "Enable"}</button></div></div>)}</div></Panel><Panel span={4}><p className="eyebrow">Owner control</p><h2>Add household member</h2><form onSubmit={add}><label>Name<input name="name" required /></label><label>Email address<input name="email" type="email" required /></label><label>Temporary password<input name="password" type="password" minLength={12} required /></label><label>Role<select name="role" defaultValue="viewer"><option value="owner">Owner</option><option value="manager">Manager</option><option value="contributor">Contributor</option><option value="viewer">Viewer</option></select></label><button className="button primary" disabled={busy}>Add member</button></form></Panel><Panel span={12}><p className="eyebrow">Household security</p><h2>Active device sessions</h2><p className="muted">Owners can revoke any device connected to this household. Each member can manage their own devices from Profile.</p>{devices.length === 0 && <p className="empty-inline">No active device sessions.</p>}{devices.map((device) => <div className="row" key={device.session_id}><div><b>{device.device_name ?? "Unnamed device"}</b><small>{memberName(device.user_id)} · Expires {new Date(device.expires_at).toLocaleDateString()}</small></div><div className="row-actions">{device.is_current && <Pill>Current device</Pill>}<button className="button compact" disabled={busy} onClick={() => revoke(device)}>{device.is_current ? "Sign out" : "Revoke"}</button></div></div>)}</Panel></div>;
}
