"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {useAppSession} from "../../../components/app-shell";
import {EmptyState,Notice,Panel,Pill} from "../../../components/ui";
import {apiRequest} from "../../../lib/client";
import {Account,Category,Merchant,money,NetWorth} from "../../../lib/ledger";
import {Debt} from "../../../lib/obligations";
import {ReportBreakdown,ReportPreset,ReportTransaction,SpendingReport} from "../../../lib/reports";

type View="spending"|"category"|"merchant"|"account"|"cash_flow"|"debt"|"net_worth";
const iso=(value:Date)=>value.toISOString().slice(0,10);
function initialFrom(){const value=new Date();value.setDate(1);return iso(value)}
function percent(current:number,prior:number){if(!prior)return current?100:0;return Math.round((current-prior)*100/Math.abs(prior))}
function Breakdown({title,items,currency,onPick}:{title:string;items:ReportBreakdown[];currency:string;onPick?:(id:string)=>void}){const maximum=Math.max(1,...items.map(item=>Math.abs(item.amount_minor)));return <Panel><p className="eyebrow">Explainable breakdown</p><h2>{title}</h2>{!items.length?<EmptyState title="No report activity">No matching spending is available for this breakdown.</EmptyState>:<div className="report-bars">{items.map(item=><button type="button" key={`${item.id}-${item.name}`} onClick={()=>onPick?.(item.id)}><span><b>{item.name}</b><small>{money(item.amount_minor,currency)}</small></span><i style={{width:`${Math.max(2,Math.abs(item.amount_minor)*100/maximum)}%`}}/></button>)}</div>}</Panel>}
function Detail({rows,currency}:{rows:ReportTransaction[];currency:string}){return <Panel><p className="eyebrow">Contributing ledger records</p><h2>{rows.length} transactions</h2>{!rows.length?<EmptyState title="Nothing contributes to this result">Change the dates or filters to inspect another period.</EmptyState>:<div className="report-table-wrap"><table className="report-table"><thead><tr><th>Date</th><th>Classification</th><th>Payee</th><th>Account</th><th>Categories</th><th>Report amount</th></tr></thead><tbody>{rows.map(row=><tr key={row.transaction_id}><td>{row.transaction_date}</td><td><Pill tone={row.classification==="spending"?"amber":row.classification==="income"?"green":"blue"}>{row.classification.replaceAll("_"," ")}</Pill></td><td><b>{row.merchant_name||row.payee||"No payee"}</b><small>{row.status}{row.activity_type!=="regular"?` · ${row.activity_type.replaceAll("_"," ")}`:""}</small></td><td>{row.account_name}</td><td>{row.categories.map(item=>item.name).join(", ")||"Uncategorized"}</td><td>{money(row.report_amount_minor,currency)}</td></tr>)}</tbody></table></div>}</Panel>}

export default function ReportsPage(){
 const {serverUrl,session,me}=useAppSession(),canExport=me.role==="owner"||me.role==="manager";
 const [view,setView]=useState<View>("spending"),[dateFrom,setDateFrom]=useState(initialFrom()),[dateTo,setDateTo]=useState(iso(new Date())),[currency,setCurrency]=useState("USD"),[scope,setScope]=useState("household"),[includePending,setIncludePending]=useState(false),[accountId,setAccountId]=useState(""),[categoryId,setCategoryId]=useState(""),[merchantId,setMerchantId]=useState("");
 const [report,setReport]=useState<SpendingReport|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[categories,setCategories]=useState<Category[]>([]),[merchants,setMerchants]=useState<Merchant[]>([]),[debts,setDebts]=useState<Debt[]>([]),[netWorth,setNetWorth]=useState<NetWorth|null>(null),[presets,setPresets]=useState<ReportPreset[]>([]),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(<T,>(path:string,init:RequestInit={})=>apiRequest<T>(serverUrl,path,init,session.access_token),[serverUrl,session.access_token]);
 const params=useMemo(()=>{const value=new URLSearchParams({date_from:dateFrom,date_to:dateTo,currency_code:currency,ownership_scope:scope,include_pending:String(includePending)});if(accountId)value.set("account_id",accountId);if(categoryId)value.set("category_id",categoryId);if(merchantId)value.set("merchant_id",merchantId);return value.toString()},[dateFrom,dateTo,currency,scope,includePending,accountId,categoryId,merchantId]);
 const loadReference=useCallback(async()=>{const [a,c,m,d,p]=await Promise.all([request<Account[]>("/v1/ledger/accounts"),request<Category[]>("/v1/ledger/categories"),request<Merchant[]>("/v1/ledger/merchants"),request<Debt[]>("/v1/obligations/debts"),request<ReportPreset[]>("/v1/reports/presets")]);setAccounts(a);setCategories(c);setMerchants(m);setDebts(d);setPresets(p)},[request]);
 const loadReport=useCallback(async()=>{setBusy(true);try{const [value,worth]=await Promise.all([request<SpendingReport>(`/v1/reports/spending?${params}`),request<NetWorth>(`/v1/ledger/net-worth?currency_code=${currency}&as_of=${dateTo}`)]);setReport(value);setNetWorth(worth);setNotice("")}catch(error){setNotice(error instanceof Error?error.message:"Report could not be loaded.")}finally{setBusy(false)}},[request,params,currency,dateTo]);
 useEffect(()=>{void loadReference().catch(error=>setNotice(error.message))},[loadReference]);useEffect(()=>{void loadReport()},[loadReport]);
 const filters={date_from:dateFrom,date_to:dateTo,currency_code:currency,ownership_scope:scope,include_pending:includePending,account_id:accountId||null,category_id:categoryId||null,merchant_id:merchantId||null};
 async function savePreset(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,data=new FormData(formElement),name=String(data.get("name")||"").trim();if(!name)return;setBusy(true);try{await request("/v1/reports/presets",{method:"POST",body:JSON.stringify({name,report_type:view,filters})});formElement.reset();await loadReference();setNotice("Report parameters saved. Financial results remain live from the ledger.")}catch(error){setNotice(error instanceof Error?error.message:"Report could not be saved.")}finally{setBusy(false)}}
 function applyPreset(item:ReportPreset){const f=item.filters;setView(item.report_type as View);setDateFrom(String(f.date_from||initialFrom()));setDateTo(String(f.date_to||iso(new Date())));setCurrency(String(f.currency_code||"USD"));setScope(String(f.ownership_scope||"household"));setIncludePending(Boolean(f.include_pending));setAccountId(String(f.account_id||""));setCategoryId(String(f.category_id||""));setMerchantId(String(f.merchant_id||""));setNotice(`Loaded “${item.name}”.`)}
 async function removePreset(id:string){setBusy(true);try{await request(`/v1/reports/presets/${id}`,{method:"DELETE"});await loadReference()}catch(error){setNotice(error instanceof Error?error.message:"Saved report could not be deleted.")}finally{setBusy(false)}}
 async function exportFile(kind:"csv"|"print"){setBusy(true);try{const response=await fetch(`${serverUrl}/v1/reports/spending${kind==="csv"?".csv":"/print"}?${params}`,{headers:{Authorization:`Bearer ${session.access_token}`}});if(!response.ok)throw new Error("Report export failed.");const url=URL.createObjectURL(await response.blob());if(kind==="print")window.open(url,"_blank","noopener,noreferrer");else{const link=document.createElement("a");link.href=url;link.download=`tallystead-spending-${dateFrom}-${dateTo}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}catch(error){setNotice(error instanceof Error?error.message:"Report export failed.")}finally{setBusy(false)}}
 const prior=report?.prior_period.totals,spendingChange=report&&prior?percent(report.totals.spending_minor,prior.spending_minor):0,incomeChange=report&&prior?percent(report.totals.income_minor,prior.income_minor):0;
 const activeBreakdown=view==="merchant"?report?.by_merchant:view==="account"?report?.by_account:report?.by_category;
 return <div className="reports-page">{notice&&<Notice title="Reports">{notice}</Notice>}<nav className="ledger-tabs" aria-label="Reports"><button className={view==="spending"?"active":""} onClick={()=>setView("spending")}>Dashboard</button><button className={view==="category"?"active":""} onClick={()=>setView("category")}>Categories</button><button className={view==="merchant"?"active":""} onClick={()=>setView("merchant")}>Merchants</button><button className={view==="account"?"active":""} onClick={()=>setView("account")}>Accounts</button><button className={view==="cash_flow"?"active":""} onClick={()=>setView("cash_flow")}>Cash flow</button><button className={view==="debt"?"active":""} onClick={()=>setView("debt")}>Debt</button><button className={view==="net_worth"?"active":""} onClick={()=>setView("net_worth")}>Net worth</button></nav>
 <Panel className="report-filter-panel"><div className="report-filters"><label>From<input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label>To<input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}><option>USD</option><option>CAD</option><option>MXN</option></select></label><label>Scope<select value={scope} onChange={e=>setScope(e.target.value)}><option value="household">Household</option><option value="business">Business</option><option value="all">All scopes (combined)</option></select></label><label>Account<select value={accountId} onChange={e=>setAccountId(e.target.value)}><option value="">All accounts</option>{accounts.filter(a=>a.currency_code===currency).map(a=><option key={a.account_id} value={a.account_id}>{a.name}</option>)}</select></label><label>Category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c.category_id} value={c.category_id}>{c.name}</option>)}</select></label><label>Merchant<select value={merchantId} onChange={e=>setMerchantId(e.target.value)}><option value="">All merchants</option>{merchants.map(m=><option key={m.merchant_id} value={m.merchant_id}>{m.name}</option>)}</select></label><label className="report-pending"><input type="checkbox" checked={includePending} onChange={e=>setIncludePending(e.target.checked)}/> Include pending</label></div><div className="row-actions">{canExport&&<button className="button compact" disabled={busy} onClick={()=>void exportFile("csv")}>Export CSV</button>}{canExport&&<button className="button compact" disabled={busy} onClick={()=>void exportFile("print")}>Print / PDF</button>}</div></Panel>
 {report&&<>{view==="spending"&&<><div className="grid report-metrics"><Panel span={4} className="metric"><small>Spending after refunds</small><div className="amount">{money(report.totals.spending_minor,currency)}</div><Pill tone={spendingChange>0?"amber":"green"}>{spendingChange>0?"+":""}{spendingChange}% vs prior</Pill></Panel><Panel span={4} className="metric"><small>Income</small><div className="amount">{money(report.totals.income_minor,currency)}</div><Pill tone={incomeChange<0?"amber":"green"}>{incomeChange>0?"+":""}{incomeChange}% vs prior</Pill></Panel><Panel span={4} className="metric"><small>Net cash flow</small><div className="amount">{money(report.totals.net_cash_flow_minor,currency)}</div><Pill tone={report.totals.net_cash_flow_minor<0?"red":"blue"}>{report.counts.included} records</Pill></Panel></div><div className="grid"><Panel span={7}><p className="eyebrow">Monthly trend</p><h2>Spending</h2><div className="monthly-bars">{report.monthly_spending.map(item=><div key={item.month}><span>{item.month}</span><i style={{height:`${Math.max(3,Math.abs(item.amount_minor)*120/Math.max(1,...report.monthly_spending.map(row=>Math.abs(row.amount_minor))))}px`}}/><b>{money(item.amount_minor,currency)}</b></div>)}</div></Panel><Panel span={5}><p className="eyebrow">Data quality</p><h2>What affects this view</h2>{report.signals.warnings.length?report.signals.warnings.map(item=><Notice key={item} title="Review">{item}</Notice>):<Notice title="Period is complete">No pending or uncategorized warnings under these filters.</Notice>}<div className="report-counts"><span>Refunds <b>{money(report.totals.refunds_minor,currency)}</b></span><span>Debt payments <b>{money(report.totals.debt_payments_minor,currency)}</b></span><span>Transfers excluded <b>{report.counts.transfers_excluded}</b></span><span>Reversals excluded <b>{report.counts.reversals_excluded}</b></span></div></Panel></div><div className="grid"><Breakdown title="Top categories" items={report.by_category.slice(0,8)} currency={currency}/><Panel><p className="eyebrow">Explainable signals</p><h2>Changes worth reviewing</h2>{!report.signals.unusual_transactions.length&&!report.signals.recurring_changes.length?<EmptyState title="No deterministic signals">No spending crossed the documented unusual-activity or period-change thresholds.</EmptyState>:<>{report.signals.unusual_transactions.map(item=><div className="row" key={item.transaction_id}><span><b>{item.merchant_name||item.payee||"Transaction"}</b><small>{item.transaction_date} · unusual amount</small></span><b>{money(item.report_amount_minor,currency)}</b></div>)}{report.signals.recurring_changes.map(item=><div className="row" key={item.name}><span><b>{item.name}</b><small>{item.change_percent>0?"Higher":"Lower"} than prior period</small></span><b>{item.change_percent>0?"+":""}{item.change_percent}%</b></div>)}</>}</Panel></div></>}
 {(view==="category"||view==="merchant"||view==="account")&&<Breakdown title={`${view[0].toUpperCase()+view.slice(1)} spending`} items={activeBreakdown||[]} currency={currency} onPick={id=>{if(view==="category"&&id!=="uncategorized")setCategoryId(id);if(view==="merchant"&&id!=="unlinked")setMerchantId(id);if(view==="account")setAccountId(id)}}/>}
 {view==="cash_flow"&&<div className="grid"><Panel span={6}><p className="eyebrow">Observed cash movement</p><h2>Income versus outflow</h2><div className="metric-row"><span>Income</span><b>{money(report.totals.income_minor,currency)}</b></div><div className="metric-row"><span>Spending after refunds</span><b>{money(report.totals.spending_minor,currency)}</b></div><div className="metric-row"><span>Debt payments</span><b>{money(report.totals.debt_payments_minor,currency)}</b></div><div className="metric-row"><span>Investment activity</span><b>{money(report.totals.investment_activity_minor,currency)}</b></div><div className="metric-row"><span>Net account movement</span><b>{money(report.totals.net_cash_flow_minor,currency)}</b></div></Panel><Panel span={6}><p className="eyebrow">Classification rules</p><h2>No hidden adjustments</h2>{report.semantics.map(item=><Notice title="Rule" key={item}>{item}</Notice>)}</Panel></div>}
 {view==="debt"&&<Panel><p className="eyebrow">Current debt report</p><h2>Balances and minimums</h2>{!debts.filter(d=>d.currency_code===currency).length?<EmptyState title="No debts in this currency">Add a debt profile to track its balance and contractual minimum separately from spending.</EmptyState>:debts.filter(d=>d.currency_code===currency).map(d=><div className="row" key={d.debt_id}><span><b>{d.name}</b><small>{d.lender||"No lender"} · {d.apr_basis_points/100}% APR · due day {d.due_day}</small></span><span className="report-debt-values"><b>{money(d.balance_minor,currency)}</b><small>{money(d.minimum_payment_minor,currency)} minimum</small></span></div>)}</Panel>}
 {view==="net_worth"&&<div className="grid"><Panel span={4} className="metric"><small>Assets</small><div className="amount">{money(netWorth?.asset_total_minor||0,currency)}</div></Panel><Panel span={4} className="metric"><small>Liabilities</small><div className="amount">{money(netWorth?.liability_total_minor||0,currency)}</div></Panel><Panel span={4} className="metric"><small>Net worth</small><div className="amount">{money(netWorth?.net_worth_minor||0,currency)}</div></Panel><Panel>{netWorth?.accounts.map(a=><div className="row" key={a.account_id}><span><b>{a.name}</b><small>{a.ownership_scope} · {a.valuation_as_of?`valued ${a.valuation_as_of}`:"ledger balance"}</small></span><b>{money(a.value_minor,currency)}</b></div>)}</Panel></div>}
 {view!=="debt"&&view!=="net_worth"&&<Detail rows={report.transactions} currency={currency}/>}</>}
 <div className="grid report-save"><Panel span={5}><p className="eyebrow">Reusable parameters</p><h2>Save this report</h2>{canExport?<form onSubmit={savePreset}><label>Name<input name="name" placeholder="Monthly household spending" required/></label><button className="button primary" disabled={busy}>Save parameters</button></form>:<Notice title="Read-only access">Owners and Managers can save shared report parameters.</Notice>}</Panel><Panel span={7}><p className="eyebrow">Saved reports</p><h2>Household views</h2>{!presets.length?<EmptyState title="No saved reports">Save filters and a report type without copying any financial results.</EmptyState>:presets.map(item=><div className="row" key={item.preset_id}><button className="link-button" onClick={()=>applyPreset(item)}><b>{item.name}</b><small>{item.report_type.replaceAll("_"," ")} · updates from the live ledger</small></button>{canExport&&<button className="button compact danger" onClick={()=>void removePreset(item.preset_id)}>Delete</button>}</div>)}</Panel></div>
 </div>
}
