"use client";

import {FormEvent,useCallback,useEffect,useMemo,useState} from "react";
import {useAppSession} from "../../../components/app-shell";
import {EmptyState,Notice,Panel,Pill} from "../../../components/ui";
import {apiRequest} from "../../../lib/client";
import {Account,money,minorUnits,today} from "../../../lib/ledger";
import {PlanDetail,PlanGoal,PlanProjection,PlanStep,PlanSummary} from "../../../lib/plans";

const strategyLabel:Record<string,string>={smallest_balance:"Debt snowball · smallest balance",highest_rate:"Debt avalanche · highest rate",custom:"Household custom order"};
const stepLabel:Record<string,string>={starter_emergency_fund:"Step 1",debt_snowball:"Step 2",full_emergency_fund:"Step 3",retirement_15_percent:"Step 4",childrens_college:"Step 5",pay_off_home:"Step 6",build_wealth_and_give:"Step 7"};

export default function GoalsPage(){
 const {serverUrl,session,me}=useAppSession(),canWrite=me.role==="owner"||me.role==="manager";
 const [plans,setPlans]=useState<PlanSummary[]>([]),[plan,setPlan]=useState<PlanDetail|null>(null),[projection,setProjection]=useState<PlanProjection|null>(null),[accounts,setAccounts]=useState<Account[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const [asOf,setAsOf]=useState(today()),[horizon,setHorizon]=useState(90),[buffer,setBuffer]=useState("0.00");
 const request=useCallback(<T,>(path:string,init:RequestInit={})=>apiRequest<T>(serverUrl,path,init,session.access_token),[serverUrl,session.access_token]);
 const loadPlan=useCallback(async(id:string)=>{const item=await request<PlanDetail>(`/v1/plans/${id}`);setPlan(item);return item},[request]);
 const load=useCallback(async()=>{const [items,available]=await Promise.all([request<PlanSummary[]>("/v1/plans"),request<Account[]>("/v1/ledger/accounts")]);setPlans(items);setAccounts(available);const selected=items.find(item=>item.status==="active")||items[0];if(selected)await loadPlan(selected.plan_id)},[request,loadPlan]);
 useEffect(()=>{void load().catch(error=>setNotice(error.message))},[load]);
 const goals=useMemo(()=>new Map((plan?.goals||[]).map(goal=>[goal.step_id,goal])),[plan]);
 async function act<T>(action:()=>Promise<T>,message:string){setBusy(true);setNotice("");try{const result=await action();setNotice(message);if(plan)await loadPlan(plan.plan_id);return result}catch(error){setNotice(error instanceof Error?error.message:"The plan could not be updated.");return null}finally{setBusy(false)}}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const created=await act(()=>request<PlanDetail>("/v1/plans",{method:"POST",body:JSON.stringify({name:form.get("name"),currency_code:form.get("currency"),effective_date:form.get("date"),debt_strategy:"smallest_balance"})}),"Your configurable seven-step plan is ready.");if(created){await load();setPlan(created)}}
 async function forecast(save=false){if(!plan)return;const cash=minorUnits(buffer);if(cash===null)return setNotice("Enter a valid protected cash buffer.");setBusy(true);try{const result=await request<PlanProjection>(`/v1/plans/${plan.plan_id}/projection`,{method:"POST",body:JSON.stringify({as_of_date:asOf,horizon_days:horizon,cash_buffer_minor:cash,include_pending:true,save_reserves:save})});setProjection(result);setNotice(save?"Goal reserves saved. They allocate available cash without moving it.":"")}catch(error){setNotice(error instanceof Error?error.message:"The plan could not be calculated.")}finally{setBusy(false)}}
 async function changeStrategy(value:string){if(!plan)return;await act(()=>request(`/v1/plans/${plan.plan_id}`,{method:"PATCH",body:JSON.stringify({debt_strategy:value,reason:"Changed the household debt payoff strategy"})}),"Debt payoff strategy updated and the prior version was preserved.");setProjection(null)}
 async function reorderDebt(debtId:string,direction:-1|1){if(!plan||!projection)return;const order=projection.debt_order.map(item=>item.debt_id),index=order.indexOf(debtId),next=index+direction;if(next<0||next>=order.length)return;[order[index],order[next]]=[order[next],order[index]];await act(()=>request(`/v1/plans/${plan.plan_id}`,{method:"PATCH",body:JSON.stringify({debt_strategy:"custom",custom_debt_order:order,reason:"Changed the household custom debt payoff order"})}),"Custom debt order saved and versioned.");setProjection(null)}
 async function stepUpdate(step:PlanStep,values:Record<string,unknown>,reason:string){if(!plan)return;await act(()=>request(`/v1/plans/${plan.plan_id}/steps/${step.step_id}`,{method:"PATCH",body:JSON.stringify({...values,reason})}),"Plan step updated and versioned.");setProjection(null)}
 async function goalUpdate(event:FormEvent<HTMLFormElement>,step:PlanStep,goal:PlanGoal){event.preventDefault();if(!plan)return;const data=new FormData(event.currentTarget),target=String(data.get("target")||"").trim(),targetMinor=target?minorUnits(target):null;if(target&&targetMinor===null)return setNotice("Enter a valid goal amount.");if(step.step_type==="emergency_months")await stepUpdate(step,{target_months:Number(data.get("months"))},"Changed emergency-fund months");else if(step.step_type==="income_percentage")await stepUpdate(step,{percentage_basis_points:Math.round(Number(data.get("percent"))*100)},"Changed retirement income percentage");await act(()=>request(`/v1/plans/${plan.plan_id}/goals/${goal.goal_id}`,{method:"PATCH",body:JSON.stringify({target_minor:targetMinor,linked_account_id:data.get("account")||null,reason:"Updated goal target or evidence account"})}),"Goal settings saved; actual and forecast progress remain separate.");setProjection(null)}
 async function allocation(event:FormEvent<HTMLFormElement>,goal:PlanGoal){event.preventDefault();if(!plan)return;const form=event.currentTarget,data=new FormData(form),amount=minorUnits(String(data.get("amount")));if(!amount||amount<1)return setNotice("Enter a positive allocation amount.");const saved=await act(()=>request(`/v1/plans/${plan.plan_id}/goals/${goal.goal_id}/allocations`,{method:"POST",body:JSON.stringify({allocation_type:data.get("type"),amount_minor:amount,allocation_date:data.get("date"),status:"planned",note:data.get("note")||null})}),"Forecast allocation added; it does not count as actual progress until supported by evidence.");if(saved)form.reset()}
 if(!plan)return <div>{notice&&<Notice title="Plans & goals">{notice}</Notice>}<Panel><p className="eyebrow">Configurable template</p><h2>Build your household plan</h2><p className="muted">Start with all seven baby steps, then change targets, order, timing, or strategy to fit your household. The template is guidance—not a locked financial philosophy.</p>{canWrite?<form className="goal-create" onSubmit={create}><label>Plan name<input name="name" defaultValue="Our seven baby steps" required/></label><label>Currency<select name="currency"><option>USD</option><option>CAD</option><option>MXN</option></select></label><label>Effective date<input name="date" type="date" defaultValue={today()} required/></label><button className="button primary" disabled={busy}>Create seven-step plan</button></form>:<EmptyState title="No plan yet">An Owner or Manager can create the household's first plan.</EmptyState>}</Panel></div>;
 return <div className="goals-page">{notice&&<Notice title="Plans & goals">{notice}</Notice>}<section className="plan-hero"><div><p className="eyebrow">{plan.template_key==="baby_steps"?"Seven baby steps":"Household plan"}</p><h2>{plan.name}</h2><p>Effective {plan.effective_date} · {plan.currency_code} · version {plan.version_count}</p></div><div className="plan-hero-controls">{plans.length>1&&<select aria-label="View plan" value={plan.plan_id} onChange={event=>{setProjection(null);void loadPlan(event.target.value)}}>{plans.map(item=><option value={item.plan_id} key={item.plan_id}>{item.name} · {item.status}</option>)}</select>}<select aria-label="Debt payoff strategy" value={plan.debt_strategy} disabled={!canWrite||busy} onChange={event=>void changeStrategy(event.target.value)}><option value="smallest_balance">Debt snowball · smallest balance</option><option value="highest_rate">Debt avalanche · highest rate</option><option value="custom">Household custom order</option></select><Pill tone={plan.status==="active"?"green":"amber"}>{plan.status}</Pill></div></section>
 <Panel className="plan-controls"><div><p className="eyebrow">Deterministic projection</p><h2>What can this plan safely reserve?</h2></div><label>As of<input type="date" value={asOf} onChange={event=>setAsOf(event.target.value)}/></label><label>Horizon<select value={horizon} onChange={event=>setHorizon(Number(event.target.value))}><option value={30}>30 days</option><option value={90}>90 days</option><option value={180}>6 months</option><option value={365}>1 year</option></select></label><label>Protected cash buffer<input value={buffer} onChange={event=>setBuffer(event.target.value)} inputMode="decimal"/></label><button className="button primary" disabled={busy} onClick={()=>void forecast(false)}>Calculate plan</button>{canWrite&&<button className="button" disabled={busy||!projection} onClick={()=>void forecast(true)}>Save reserves</button>}</Panel>
 {projection&&<div className="grid plan-metrics"><Panel span={3}><p className="eyebrow">After obligations</p><p className="amount">{money(projection.safe_to_spend_before_goals_minor,plan.currency_code)}</p><small>Cash Planner safe to spend before goals.</small></Panel><Panel span={3}><p className="eyebrow">Goal reserves</p><p className="amount">{money(projection.allocated_to_goals_minor,plan.currency_code)}</p><small>Recommended allocation; no money moved.</small></Panel><Panel span={3}><p className="eyebrow">Remaining</p><p className="amount">{money(projection.safe_to_spend_after_goals_minor,plan.currency_code)}</p><small>After this plan's recommended reserves.</small></Panel><Panel span={3} className={projection.overcommitment_minor?"shortfall-panel":""}><p className="eyebrow">Overcommitment</p><p className="amount">{money(projection.overcommitment_minor,plan.currency_code)}</p><small>{projection.overcommitment_minor?"Targets exceed currently allocatable cash.":"No goal allocation shortfall."}</small></Panel></div>}
 <div className="plan-layout"><main className="plan-step-list">{[...plan.steps].sort((a,b)=>a.position-b.position).map((step,index)=>{const goal=goals.get(step.step_id);if(!goal)return null;const projected=projection?.steps.find(item=>item.step_id===step.step_id);return <article className={`panel plan-step${step.is_paused?" paused":""}`} key={step.step_id}><div className="plan-step-head"><span className="step-number">{step.position}</span><div><p className="eyebrow">{stepLabel[step.step_key]||`Priority ${step.position}`}</p><h2>{step.title}</h2><p className="muted">{step.description}</p></div><Pill tone={step.status==="complete"?"green":step.is_paused?"amber":"blue"}>{step.is_paused?"paused":step.status}</Pill></div>{projected&&<><div className="goal-progress"><i style={{width:`${projected.progress_percent}%`}}/><span>{projected.progress_percent}% actual progress</span></div><div className="goal-values"><span><small>Actual evidence</small><b>{money(projected.actual_funded_minor,plan.currency_code)}</b></span><span><small>Target</small><b>{projected.target_minor===null?"Needs setup":money(projected.target_minor,plan.currency_code)}</b></span><span><small>Recommended now</small><b>{money(projected.recommended_reserve_minor,plan.currency_code)}</b></span><span><small>Shortfall</small><b>{money(projected.shortfall_minor,plan.currency_code)}</b></span></div><p className="plan-basis">{projected.target_basis}{projected.actual_evidence.length?` · ${projected.actual_evidence.join("; ")}`:" · No actual funding evidence yet"}{projected.forecast_completion_date?` · forecast completion ${projected.forecast_completion_date}`:" · add a recurring allocation to forecast completion"}</p></>}
 {canWrite&&<details className="step-settings"><summary>Adjust this step</summary><form onSubmit={event=>void goalUpdate(event,step,goal)}><label>Goal target<input name="target" inputMode="decimal" defaultValue={goal.target_minor===null?"":(goal.target_minor/100).toFixed(2)} placeholder="Use calculated target"/></label>{step.step_type==="emergency_months"&&<label>Months of expenses<select name="months" defaultValue={step.target_months||3}><option value={3}>3 months</option><option value={4}>4 months</option><option value={5}>5 months</option><option value={6}>6 months</option></select></label>}{step.step_type==="income_percentage"&&<label>Income percentage<input name="percent" type="number" min="0" max="100" step="0.1" defaultValue={(step.percentage_basis_points||1500)/100}/></label>}<label>Actual-progress account<select name="account" defaultValue={goal.linked_account_id||""}><option value="">Confirmed allocations only</option>{accounts.filter(account=>account.currency_code===plan.currency_code&&!account.is_archived).map(account=><option value={account.account_id} key={account.account_id}>{account.name}</option>)}</select></label><button className="button compact primary" disabled={busy}>Save goal</button></form><form className="allocation-form" onSubmit={event=>void allocation(event,goal)}><label>Planned amount<input name="amount" inputMode="decimal" required/></label><label>Type<select name="type"><option value="one_time">One time</option><option value="recurring">Recurring</option><option value="transfer">Planned transfer</option></select></label><label>Date<input name="date" type="date" defaultValue={today()} required/></label><label>Note<input name="note" placeholder="Optional"/></label><button className="button compact" disabled={busy}>Add forecast allocation</button></form><div className="step-actions"><button className="button compact" disabled={busy||index===0} onClick={()=>void stepUpdate(step,{position:step.position-1},"Moved plan step earlier")}>Move up</button><button className="button compact" disabled={busy||index===plan.steps.length-1} onClick={()=>void stepUpdate(step,{position:step.position+1},"Moved plan step later")}>Move down</button><button className="button compact" disabled={busy} onClick={()=>void stepUpdate(step,{is_paused:!step.is_paused},step.is_paused?"Resumed plan step":"Paused plan step")}>{step.is_paused?"Resume":"Pause"}</button><button className="button compact" disabled={busy} onClick={()=>void stepUpdate(step,{status:step.status==="complete"?"active":"complete"},step.status==="complete"?"Reopened plan step":"Marked plan step complete")}>{step.status==="complete"?"Reopen":"Mark complete"}</button></div></details>}</article>})}</main>
 <aside className="plan-side"><Panel><p className="eyebrow">Debt strategy</p><h2>{strategyLabel[plan.debt_strategy]}</h2>{!projection?<p className="muted">Calculate the plan to see the current payoff order.</p>:!projection.debt_order.length?<EmptyState title="No non-mortgage debt">The snowball step currently has no active debt to order.</EmptyState>:projection.debt_order.map((debt,index)=><div className="debt-order" key={debt.debt_id}><span>{index+1}</span><div><b>{debt.name}</b><small>{money(debt.balance_minor,plan.currency_code)} · {(debt.apr_basis_points/100).toFixed(2)}% APR · {money(debt.minimum_payment_minor,plan.currency_code)} minimum</small>{canWrite&&<div className="debt-order-actions"><button aria-label={`Move ${debt.name} up`} disabled={busy||index===0} onClick={()=>void reorderDebt(debt.debt_id,-1)}>↑</button><button aria-label={`Move ${debt.name} down`} disabled={busy||index===projection.debt_order.length-1} onClick={()=>void reorderDebt(debt.debt_id,1)}>↓</button></div>}</div></div>)}</Panel><Panel><p className="eyebrow">Version history</p><h2>Plan changes</h2>{plan.versions.map(version=><div className="version-row" key={version.version_id}><b>Version {version.version_number}</b><span>{version.reason}</span><small>{version.created_at.slice(0,10)}</small></div>)}</Panel><Panel><p className="eyebrow">Boundaries</p><h2>What this plan does</h2><p className="muted">It recommends transparent allocations after required obligations. It does not move money, change balances, pay debt, or hide a shortfall.</p></Panel></aside></div></div>;
}
