"use client";

import {useCallback,useEffect,useState} from "react";
import {CategoryRule,CategorySuggestion} from "../lib/assistant";
import {apiRequest} from "../lib/client";
import {Category,money} from "../lib/ledger";
import {useAppSession} from "./app-shell";
import {EmptyState,Notice,Pill} from "./ui";

export default function CategorizationReview(){
 const {serverUrl,session,me}=useAppSession(),canReview=me.role==="owner"||me.role==="manager";
 const [suggestions,setSuggestions]=useState<CategorySuggestion[]>([]),[rules,setRules]=useState<CategoryRule[]>([]),[categories,setCategories]=useState<Category[]>([]),[selected,setSelected]=useState<string[]>([]),[edits,setEdits]=useState<Record<string,string>>({}),[useAi,setUseAi]=useState(false),[showRules,setShowRules]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 const request=useCallback(<T,>(path:string,init:RequestInit={})=>apiRequest<T>(serverUrl,path,init,session.access_token),[serverUrl,session.access_token]);
 const load=useCallback(async()=>{const [items,learned,available]=await Promise.all([request<CategorySuggestion[]>("/v1/categorization/suggestions"),request<CategoryRule[]>("/v1/categorization/rules"),request<Category[]>("/v1/ledger/categories")]);setSuggestions(items);setRules(learned);setCategories(available)},[request]);
 useEffect(()=>{void load().catch(error=>setNotice(error.message))},[load]);
 async function generate(){setBusy(true);try{const created=await request<CategorySuggestion[]>("/v1/categorization/suggestions/generate",{method:"POST",body:JSON.stringify({use_ai:useAi})});setNotice(created.length?`${created.length} reviewable suggestion(s) created.`:"No additional evidence-backed suggestions were available.");await load()}catch(error){setNotice(error instanceof Error?error.message:"Suggestions could not be generated.")}finally{setBusy(false)}}
 async function decide(item:CategorySuggestion,action:"accept"|"reject"){setBusy(true);try{const categoryId=edits[item.suggestion_id]||item.proposed_splits[0]?.category_id;await request(`/v1/categorization/suggestions/${item.suggestion_id}/review`,{method:"PUT",body:JSON.stringify({action,learn_rule:true,...(action==="accept"&&categoryId?{splits:[{category_id:categoryId,amount_minor:item.amount_minor}]}:{})})});setNotice(action==="accept"?"Category applied after your review.":"Suggestion rejected; the transaction was unchanged.");await load()}catch(error){setNotice(error instanceof Error?error.message:"Suggestion could not be reviewed.")}finally{setBusy(false)}}
 async function batch(action:"accept"|"reject"){setBusy(true);try{await request("/v1/categorization/suggestions/review-batch",{method:"PUT",body:JSON.stringify({suggestion_ids:selected,action,learn_rule:true})});setSelected([]);await load()}catch(error){setNotice(error instanceof Error?error.message:"Selected suggestions could not be reviewed.")}finally{setBusy(false)}}
 async function toggleRule(item:CategoryRule){await request(`/v1/categorization/rules/${item.rule_id}`,{method:"PATCH",body:JSON.stringify({is_active:!item.is_active})});await load()}
 async function removeRule(item:CategoryRule){await request(`/v1/categorization/rules/${item.rule_id}`,{method:"DELETE"});await load()}
 return <div>{notice&&<Notice title="Categorization review">{notice}</Notice>}<div className="assistant-review-toolbar"><div><Pill tone="blue">Suggestion only</Pill><p className="muted">Rules and local AI propose categories. Nothing changes until an Owner or Manager accepts it.</p></div><div className="row-actions"><button className={`button compact${showRules?" active":""}`} onClick={()=>setShowRules(!showRules)}>Learned rules ({rules.length})</button>{canReview&&<label className="ai-review-toggle"><input type="checkbox" checked={useAi} onChange={event=>setUseAi(event.target.checked)}/> Use local AI when rules have no answer</label>}{canReview&&<button className="button primary" disabled={busy} onClick={()=>void generate()}>Find suggestions</button>}</div></div>
 {showRules&&<section className="panel assistant-rules"><p className="eyebrow">Accepted household decisions</p><h2>Editable learned rules</h2>{!rules.length?<EmptyState title="No learned rules">Accept a suggestion with learning enabled to create a reversible merchant or payee rule.</EmptyState>:rules.map(item=><div className="row" key={item.rule_id}><span><b>{item.match_type}: {item.match_value}</b><small>{item.direction==="out"?"Money out":"Money in"} → {item.category_name}</small></span>{canReview&&<div className="row-actions"><button className="button compact" onClick={()=>void toggleRule(item)}>{item.is_active?"Disable":"Enable"}</button><button className="button compact danger" onClick={()=>void removeRule(item)}>Delete</button></div>}</div>)}</section>}
 {selected.length>0&&canReview&&<div className="batch-bar"><b>{selected.length} selected</b><button className="button compact primary" disabled={busy} onClick={()=>void batch("accept")}>Accept proposed</button><button className="button compact" disabled={busy} onClick={()=>void batch("reject")}>Reject</button></div>}
 <div className="assistant-suggestion-list">{!suggestions.length?<EmptyState title="No suggestions waiting">Uncategorized transactions remain available for manual categorization. Run the evidence check when you want assistance.</EmptyState>:suggestions.map(item=>{const direction=item.amount_minor>0?"income":"expense",options=categories.filter(category=>category.category_type===direction&&!category.is_archived);return <article className="panel suggestion-card" key={item.suggestion_id}>{canReview&&<input aria-label={`Select ${item.payee||"transaction"}`} type="checkbox" checked={selected.includes(item.suggestion_id)} onChange={event=>setSelected(value=>event.target.checked?[...value,item.suggestion_id]:value.filter(id=>id!==item.suggestion_id))}/>}<div className="suggestion-main"><div className="row"><span><b>{item.payee||"No payee"}</b><small>{item.transaction_date} · {item.provider==="rules"?"Household evidence":`Local AI · ${item.model_version}`}</small></span><b>{money(item.amount_minor,item.currency_code)}</b></div><div className="suggestion-choice"><span>Suggested category</span><select disabled={!canReview} value={edits[item.suggestion_id]||item.proposed_splits[0]?.category_id||""} onChange={event=>setEdits(value=>({...value,[item.suggestion_id]:event.target.value}))}>{options.map(category=><option value={category.category_id} key={category.category_id}>{category.name}</option>)}</select><Pill tone={item.confidence_percent>=90?"green":item.confidence_percent>=70?"blue":"amber"}>{item.confidence_percent}% confidence</Pill></div><ul className="suggestion-evidence">{item.evidence.map(evidence=><li key={evidence}>{evidence}</li>)}</ul>{canReview&&<div className="row-actions"><button className="button primary compact" disabled={busy} onClick={()=>void decide(item,"accept")}>Accept</button><button className="button compact" disabled={busy} onClick={()=>void decide(item,"reject")}>Reject</button></div>}</div></article>})}</div>
 </div>
}
