"use client";

import { FormEvent, useMemo, useState } from "react";
import { useAppSession } from "./app-shell";
import { apiRequest } from "../lib/client";
import { EffectPreview, ReviewItem } from "../lib/imports";
import { Account, Category, money, Transaction } from "../lib/ledger";
import { Debt } from "../lib/obligations";

type ResolutionType = "tracked_account"|"external_owned_account"|"payment"|"gift"|"loan_or_repayment"|"income_or_spending"|"reimbursement"|"not_transfer";

export default function TransferResolver({row,accounts,categories,debts,transactions,pendingRows,onChanged}:{row:ReviewItem;accounts:Account[];categories:Category[];debts:Debt[];transactions:Transaction[];pendingRows:ReviewItem[];onChanged:()=>void|Promise<void>}){
  const {serverUrl,session}=useAppSession();
  const [open,setOpen]=useState(false),[kind,setKind]=useState<ResolutionType>("tracked_account"),[preview,setPreview]=useState<EffectPreview|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const sourceAccount=accounts.find(item=>item.account_id===row.source_account_id);
  const oppositeTransactions=useMemo(()=>transactions.filter(item=>item.account_id!==row.source_account_id&&item.currency_code===row.currency_code&&item.amount_minor===-(row.amount_minor??0)&&!item.transfer_id),[transactions,row]);
  const oppositeRows=useMemo(()=>pendingRows.filter(item=>item.row_id!==row.row_id&&item.source_account_id!==row.source_account_id&&item.currency_code===row.currency_code&&item.amount_minor===-(row.amount_minor??0)),[pendingRows,row]);
  const refundExpenses=useMemo(()=>{
    const refundAmount=Math.max(row.amount_minor??0,0),refundDateText=row.transaction_date??"9999-12-31",refundDate=Date.parse(`${refundDateText}T00:00:00`);
    const candidates=transactions.filter(item=>item.amount_minor<0&&item.currency_code===row.currency_code&&!item.transfer_id);
    const distance=(item:Transaction)=>Math.abs(Date.parse(`${item.transaction_date}T00:00:00`)-refundDate);
    const compare=(a:Transaction,b:Transaction)=>distance(a)-distance(b)||(Math.abs(a.amount_minor)-refundAmount)-(Math.abs(b.amount_minor)-refundAmount)||a.transaction_id.localeCompare(b.transaction_id);
    const likely=candidates.filter(item=>item.transaction_date<=refundDateText&&Math.abs(item.amount_minor)>=refundAmount).sort(compare);
    const likelyIds=new Set(likely.map(item=>item.transaction_id));
    return {likely,others:candidates.filter(item=>!likelyIds.has(item.transaction_id)).sort(compare)};
  },[transactions,row.amount_minor,row.currency_code,row.transaction_date]);
  function payload(form:HTMLFormElement){const data=new FormData(form),opposite=String(data.get("opposite")||"");return {row_id:row.row_id,resolution_type:kind,counterparty_transaction_id:opposite.startsWith("transaction:")?opposite.slice(12):null,counterparty_import_row_id:opposite.startsWith("row:")?opposite.slice(4):null,counterparty_account_id:opposite.startsWith("account:")?opposite.slice(8):null,category_id:data.get("category")||null,original_transaction_id:data.get("original")||null,debt_id:data.get("debt")||null,amount_minor:data.get("amount")?Math.round(Number(data.get("amount"))*100):null}}
  async function calculate(form:HTMLFormElement){if(!form.reportValidity())return;setBusy(true);setNotice("");try{setPreview(await apiRequest<EffectPreview>(serverUrl,"/v1/automation/transfer-resolutions/preview",{method:"POST",body:JSON.stringify(payload(form))},session.access_token));setNotice("Review the effects, then confirm.")}catch(error){setNotice(error instanceof Error?error.message:"The transfer could not be previewed.")}finally{setBusy(false)}}
  async function resolve(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;if(!preview){await calculate(form);return}setBusy(true);setNotice("");try{await apiRequest(serverUrl,"/v1/automation/transfer-resolutions",{method:"POST",body:JSON.stringify(payload(form))},session.access_token);setOpen(false);setPreview(null);await onChanged()}catch(error){setNotice(error instanceof Error?error.message:"The transfer could not be resolved.")}finally{setBusy(false)}}
  if(!open)return <button type="button" className="button compact" onClick={()=>setOpen(true)}>Resolve transfer</button>;
  const direction=(row.amount_minor??0)>0?"income":"expense";
  const eligibleCategories=categories.filter(item=>item.category_type===direction);
  return <form className="transfer-resolver" onSubmit={resolve} onChange={()=>setPreview(null)}>
    <div className="title-with-status"><div><b>Resolve transfer</b><small>{sourceAccount?.name||row.source_name} · {row.amount_minor==null?"—":money(row.amount_minor,row.currency_code)}</small></div><button type="button" className="button compact" onClick={()=>{setOpen(false);setPreview(null)}}>Cancel</button></div>
    <label>What is this movement?<select value={kind} onChange={event=>setKind(event.target.value as ResolutionType)}><option value="tracked_account">Between my tracked accounts</option><option value="external_owned_account">To/from my untracked account</option><option value="payment">Payment to another person or business</option><option value="reimbursement">Reimbursement or refund</option><option value="gift">Gift</option><option value="loan_or_repayment">Loan or repayment</option><option value="income_or_spending">Regular income or spending</option><option value="not_transfer">Not a transfer — categorize normally</option></select></label>
    {kind==="tracked_account"&&<label>Opposite side<select name="opposite" required><option value="">Choose an existing match or tracked account</option>{oppositeRows.map(item=><option key={item.row_id} value={`row:${item.row_id}`}>Pending: {item.raw_payee||item.source_name} · {item.transaction_date} · {money(item.amount_minor!,item.currency_code)}</option>)}{oppositeTransactions.map(item=><option key={item.transaction_id} value={`transaction:${item.transaction_id}`}>Recorded: {item.payee||"Transaction"} · {item.transaction_date} · {money(item.amount_minor,item.currency_code)}</option>)}{accounts.filter(item=>item.account_id!==row.source_account_id&&item.currency_code===row.currency_code&&!item.is_archived).map(item=><option key={item.account_id} value={`account:${item.account_id}`}>Create missing side in {item.name}</option>)}</select><small>Exact opposite pending or recorded entries appear first. Choosing an account creates the missing ledger leg.</small></label>}
    {kind==="external_owned_account"&&<p className="muted">This changes the tracked account balance but is excluded from household income and spending.</p>}
    {kind==="loan_or_repayment"&&<label>Loan or debt<select name="debt" required><option value="">Choose a loan or debt</option>{debts.filter(item=>item.is_active&&item.currency_code===row.currency_code).map(item=><option key={item.debt_id} value={item.debt_id}>{item.name}{item.lender?` — ${item.lender}`:""} · {money(item.balance_minor,item.currency_code)}</option>)}</select><small>This links the imported money-out transaction to the tracked debt and its nearest payment obligation.</small></label>}
    {kind==="reimbursement"&&<><label>Original expense<select name="original" required><option value="">Choose original expense</option>{refundExpenses.likely.length>0&&<optgroup label="Nearby purchases large enough for this refund">{refundExpenses.likely.map(item=><option key={item.transaction_id} value={item.transaction_id}>{item.transaction_date} · {item.payee||"Expense"} · {money(item.amount_minor,item.currency_code)}</option>)}</optgroup>}{refundExpenses.others.length>0&&<optgroup label="Other expenses">{refundExpenses.others.map(item=><option key={item.transaction_id} value={item.transaction_id}>{item.transaction_date} · {item.payee||"Expense"} · {money(item.amount_minor,item.currency_code)}</option>)}</optgroup>}</select><small>Earlier purchases that can cover the full refund are listed first by closest date. Other same-currency expenses follow.</small></label><label>Expense category<select name="category" required><option value="">Choose category</option>{categories.filter(item=>item.category_type==="expense").map(item=><option key={item.category_id} value={item.category_id}>{item.name}</option>)}</select></label><label>Amount received<input name="amount" type="number" min="0.01" step="0.01" defaultValue={((row.amount_minor??0)/100).toFixed(2)} required/></label></>}
    {!['tracked_account','external_owned_account','reimbursement','loan_or_repayment'].includes(kind)&&<label>{direction==="income"?"Income":"Expense"} category<select name="category" required><option value="">Choose category</option>{eligibleCategories.map(item=><option key={item.category_id} value={item.category_id}>{item.name}</option>)}</select></label>}
    {preview&&<div className="effect-preview"><b>Effect preview</b><small>{preview.report_effect}</small><small>{preview.reconciliation_effect}</small><small>Tracked balance change: {money(preview.account_balances_change_minor,row.currency_code)}</small></div>}
    <div className="row-actions"><button type="button" className="button" disabled={busy} onClick={event=>void calculate(event.currentTarget.form!)}>Preview</button><button className="button primary" disabled={busy||!preview}>Confirm resolution</button></div>{notice&&<small>{notice}</small>}
  </form>
}
