"use client";

import { KeyboardEvent, useEffect, useState } from "react";
import { apiRequest } from "../lib/client";
import { money, Transaction } from "../lib/ledger";

type TransactionPage = {items:Transaction[];page:number;page_size:number;total_items:number;total_pages:number};
type Props = {name:string;label:string;serverUrl:string;accessToken:string;direction?:"inflow"|"outflow";currencyCode?:string;amountMinor?:number;excludeAccountId?:string;hasSplits?:boolean;onChange?:(transaction:Transaction|null)=>void;help?:string;required?:boolean};

export default function TransactionPicker({name,label,serverUrl,accessToken,direction,currencyCode,amountMinor,excludeAccountId,hasSplits,onChange,help,required=true}:Props){
  const [query,setQuery]=useState(""),[page,setPage]=useState(1),[result,setResult]=useState<TransactionPage|null>(null),[selected,setSelected]=useState<Transaction|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const filterKey=[direction,currencyCode,amountMinor,excludeAccountId,hasSplits].join(":");
  useEffect(()=>{setResult(null);setSelected(null);setPage(1)},[filterKey]);
  async function search(nextPage=1){setBusy(true);setError("");try{const params=new URLSearchParams({page:String(nextPage),page_size:"20",transaction_status:"posted",has_transfer:"false"});if(query.trim())params.set("search",query.trim());if(direction)params.set("direction",direction);if(currencyCode)params.set("currency_code",currencyCode);if(amountMinor!==undefined)params.set("amount_minor",String(amountMinor));if(excludeAccountId)params.set("exclude_account_id",excludeAccountId);if(hasSplits!==undefined)params.set("has_splits",String(hasSplits));const value=await apiRequest<TransactionPage>(serverUrl,`/v1/ledger/transactions/page?${params}`,{},accessToken);setResult(value);setPage(value.page)}catch(reason){setError(reason instanceof Error?reason.message:"Transactions could not be searched.")}finally{setBusy(false)}}
  function choose(transaction:Transaction|null){setSelected(transaction);onChange?.(transaction)}
  function onKeyDown(event:KeyboardEvent<HTMLInputElement>){if(event.key==="Enter"){event.preventDefault();void search(1)}}
  return <div className="transaction-picker"><label>{label}<input value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={onKeyDown} placeholder="Search payee, account, category, or memo"/></label><input type="hidden" name={name} value={selected?.transaction_id??""} required={required}/><div className="row-actions"><button type="button" className="button compact" disabled={busy} onClick={()=>void search(1)}>{busy?"Searching…":"Search transactions"}</button>{selected&&<button type="button" className="button compact" onClick={()=>choose(null)}>Clear</button>}</div>{help&&<small>{help}</small>}{error&&<small role="alert">{error}</small>}{selected&&<div className="candidate-row"><div><b>Selected: {selected.payee||"Transaction"}</b><small>{selected.transaction_date} · {selected.account_name} · {money(selected.amount_minor,selected.currency_code)}</small></div></div>}{result&&<div className="candidate-suggestions">{result.items.length===0?<small>No compatible transactions found.</small>:result.items.map(item=><button type="button" className="candidate-row transaction-candidate-button" key={item.transaction_id} onClick={()=>choose(item)}><span><b>{item.payee||"Transaction"}</b><small>{item.transaction_date} · {item.account_name} · {money(item.amount_minor,item.currency_code)}</small></span><span>{selected?.transaction_id===item.transaction_id?"Selected":"Choose"}</span></button>)}{result.total_pages>1&&<div className="row-actions"><button type="button" className="button compact" disabled={busy||page<=1} onClick={()=>void search(page-1)}>Previous</button><small>Page {page} of {result.total_pages} · {result.total_items} matches</small><button type="button" className="button compact" disabled={busy||page>=result.total_pages} onClick={()=>void search(page+1)}>Next</button></div>}</div>}</div>;
}
