"use client";

import { FormEvent, useMemo, useState } from "react";
import TransactionPicker from "./transaction-picker";
import { useAppSession } from "./app-shell";
import { apiRequest } from "../lib/client";
import { EffectPreview, ReviewItem } from "../lib/imports";
import { Account, Category, money } from "../lib/ledger";
import { Debt } from "../lib/obligations";

type ResolutionType = "tracked_account"|"external_owned_account"|"payment"|"gift"|"loan_or_repayment"|"income_or_spending"|"reimbursement"|"not_transfer";

export default function TransferResolver({row,accounts,categories,debts,pendingRows,onChanged}:{row:ReviewItem;accounts:Account[];categories:Category[];debts:Debt[];pendingRows:ReviewItem[];onChanged:()=>void|Promise<void>}){
  const {serverUrl,session}=useAppSession();
  const [open,setOpen]=useState(false),[kind,setKind]=useState<ResolutionType>("tracked_account"),[preview,setPreview]=useState<EffectPreview|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const sourceAccount=accounts.find(item=>item.account_id===row.source_account_id);
  const oppositeRows=useMemo(()=>pendingRows.filter(item=>item.row_id!==row.row_id&&item.source_account_id!==row.source_account_id&&item.currency_code===row.currency_code&&item.amount_minor===-(row.amount_minor??0)),[pendingRows,row]);
  function payload(form:HTMLFormElement){const data=new FormData(form),recorded=String(data.get("recorded")||""),opposite=recorded||String(data.get("opposite")||"");return {row_id:row.row_id,resolution_type:kind,counterparty_transaction_id:recorded|| (opposite.startsWith("transaction:")?opposite.slice(12):null),counterparty_import_row_id:opposite.startsWith("row:")?opposite.slice(4):null,counterparty_account_id:opposite.startsWith("account:")?opposite.slice(8):null,category_id:data.get("category")||null,original_transaction_id:data.get("original")||null,debt_id:data.get("debt")||null,amount_minor:data.get("amount")?Math.round(Number(data.get("amount"))*100):null,principal_amount_minor:data.get("principal")!==null&&data.get("principal")!==""?Math.round(Number(data.get("principal"))*100):null}}
  async function calculate(form:HTMLFormElement){if(!form.reportValidity())return;setBusy(true);setNotice("");try{setPreview(await apiRequest<EffectPreview>(serverUrl,"/v1/automation/transfer-resolutions/preview",{method:"POST",body:JSON.stringify(payload(form))},session.access_token));setNotice("Review the effects, then confirm.")}catch(error){setNotice(error instanceof Error?error.message:"The transfer could not be previewed.")}finally{setBusy(false)}}
  async function resolve(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;if(!preview){await calculate(form);return}setBusy(true);setNotice("");try{await apiRequest(serverUrl,"/v1/automation/transfer-resolutions",{method:"POST",body:JSON.stringify(payload(form))},session.access_token);setOpen(false);setPreview(null);await onChanged()}catch(error){setNotice(error instanceof Error?error.message:"The transfer could not be resolved.")}finally{setBusy(false)}}
  if(!open)return <button type="button" className="button compact" onClick={()=>setOpen(true)}>Resolve transfer</button>;
  const direction=(row.amount_minor??0)>0?"income":"expense";
  const eligibleCategories=categories.filter(item=>item.category_type===direction);
  return <form className="transfer-resolver" onSubmit={resolve} onChange={()=>setPreview(null)}>
    <div className="title-with-status"><div><b>Resolve transfer</b><small>{sourceAccount?.name||row.source_name} · {row.amount_minor==null?"—":money(row.amount_minor,row.currency_code)}</small></div><button type="button" className="button compact" onClick={()=>{setOpen(false);setPreview(null)}}>Cancel</button></div>
    <label>What is this movement?<select value={kind} onChange={event=>setKind(event.target.value as ResolutionType)}><option value="tracked_account">Between my tracked accounts</option><option value="external_owned_account">To/from my untracked account</option><option value="payment">Payment to another person or business</option><option value="reimbursement">Reimbursement or refund</option><option value="gift">Gift</option><option value="loan_or_repayment">Loan or repayment</option><option value="income_or_spending">Regular income or spending</option><option value="not_transfer">Not a transfer — categorize normally</option></select></label>
    {kind==="tracked_account"&&<><label>Pending match or destination account<select name="opposite"><option value="">Search recorded transactions below</option>{oppositeRows.map(item=><option key={item.row_id} value={`row:${item.row_id}`}>Pending: {item.raw_payee||item.source_name} · {item.transaction_date} · {money(item.amount_minor!,item.currency_code)}</option>)}{accounts.filter(item=>item.account_id!==row.source_account_id&&item.currency_code===row.currency_code&&!item.is_archived).map(item=><option key={item.account_id} value={`account:${item.account_id}`}>Create missing side in {item.name}</option>)}</select></label><TransactionPicker name="recorded" label="Or search an existing recorded match" serverUrl={serverUrl} accessToken={session.access_token} currencyCode={row.currency_code} amountMinor={-(row.amount_minor??0)} excludeAccountId={row.source_account_id} required={false} help="Only exact opposite, same-currency transactions from another account are returned."/></>}
    {kind==="external_owned_account"&&<p className="muted">This changes the tracked account balance but is excluded from household income and spending.</p>}
    {kind==="loan_or_repayment"&&<label>Loan or debt<select name="debt" required><option value="">Choose a loan or debt</option>{debts.filter(item=>item.is_active&&item.currency_code===row.currency_code).map(item=><option key={item.debt_id} value={item.debt_id}>{item.name}{item.lender?` — ${item.lender}`:""} · {money(item.balance_minor,item.currency_code)}</option>)}</select><small>This links the imported money-out transaction to the tracked debt and its nearest payment obligation.</small></label>}
    {kind==="loan_or_repayment"&&<label>Principal reducing the balance<input name="principal" type="number" min="0" max={Math.abs(row.amount_minor??0)/100} step="0.01" defaultValue={(Math.abs(row.amount_minor??0)/100).toFixed(2)} required/><small>Use the principal shown on the statement. The full payment still counts as spending; only this amount lowers the debt.</small></label>}
    {kind==="reimbursement"&&<><TransactionPicker name="original" label="Original expense" serverUrl={serverUrl} accessToken={session.access_token} direction="outflow" currencyCode={row.currency_code} help="Searches all compatible expenses, including older imports."/><label>Expense category<select name="category" required><option value="">Choose category</option>{categories.filter(item=>item.category_type==="expense").map(item=><option key={item.category_id} value={item.category_id}>{item.name}</option>)}</select></label><label>Amount received<input name="amount" type="number" min="0.01" step="0.01" defaultValue={((row.amount_minor??0)/100).toFixed(2)} required/></label></>}
    {!['tracked_account','external_owned_account','reimbursement'].includes(kind)&&<label>{kind==="loan_or_repayment"?"Loan payment":direction==="income"?"Income":"Expense"} category<select name="category" required><option value="">Choose category</option>{eligibleCategories.map(item=><option key={item.category_id} value={item.category_id}>{item.name}</option>)}</select>{kind==="loan_or_repayment"&&<small>The transaction remains classified as debt payoff activity while using this category, such as Housing, for organization and filtered reports.</small>}</label>}
    {preview&&<div className="effect-preview"><b>Effect preview</b><small>{preview.report_effect}</small><small>{preview.reconciliation_effect}</small><small>Tracked balance change: {money(preview.account_balances_change_minor,row.currency_code)}</small></div>}
    <div className="row-actions"><button type="button" className="button" disabled={busy} onClick={event=>void calculate(event.currentTarget.form!)}>Preview</button><button className="button primary" disabled={busy||!preview}>Confirm resolution</button></div>{notice&&<small>{notice}</small>}
  </form>
}
